=== rainlanguage/orderbook-subgraph/schema/meta/v0/contract.meta.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ContractMetadata",
  "$comment": "v0.0.1",
  "definitions": {
    "ContractMetadata": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Contract Name"
        },
        "abiName": {
          "type": "string",
          "title": "Contract ABI name",
          "description": "Name of the contract corresponding to `contractName` feild in the abi"
        },
        "desc": {
          "type": "string",
          "title": "Contract Description",
          "description": "A brief description about the contract."
        },
        "alias": {
          "type": "string",
          "title": "Contract Alias",
          "description": "Alias of the contract used by RainLang, follows RainLang word pattern.",
          "pattern": "^[a-z][a-z0-9-]*$"
        },
        "source": {
          "type": "string",
          "title": "Contract Source",
          "description": "Github repository URL where this contract belongs to."
        },
        "methods": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Method"
          },
          "title": "Contract Methods",
          "description": "Methods of the contract that receive at least one expression (EvaluableConfig) from arguments.",
          "minItems": 1
        }
      },
      "required": ["name", "abiName", "desc", "alias", "source", "methods"],
      "additionalProperties": false,
      "title": "Rain Contract Metadata",
      "description": "Required info about a contract that receives expression in at least one of its methods."
    },
    "Method": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Method Name"
        },
        "abiName": {
          "type": "string",
          "title": "Method ABI Name",
          "description": "Name of the method corresponding to `name` feild in the abi"
        },
        "desc": {
          "type": "string",
          "title": "Method Description"
        },
        "inputs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Input"
          },
          "title": "Method Inputs",
          "minItems": 1
        },
        "expressions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Expression"
          },
          "title": "Method Expressions",
          "minItems": 1
        }
      },
      "required": ["name", "abiName", "desc", "expressions"],
      "additionalProperties": false
    },
    "Input": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Input Name"
        },
        "abiName": {
          "type": "string",
          "title": "Input ABI Name",
          "description": "Name of the input corresponding to `name` feild in the abi"
        },
        "desc": {
          "type": "string",
          "title": "Input Description"
        },
        "path": {
          "type": "string",
          "title": "Input Path",
          "description": "Input's path in contract's ABI."
        }
      },
      "required": ["name", "abiName", "desc", "path"],
      "additionalProperties": false
    },
    "Expression": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Expression Name"
        },
        "abiName": {
          "type": "string",
          "title": "Expression ABI Name",
          "description": "Name of the expression corresponding to `name` feild in the abi"
        },
        "desc": {
          "type": "string",
          "title": "Expression Description"
        },
        "path": {
          "type": "string",
          "title": "Expression Path",
          "description": "Expression's path in contract's ABI."
        },
        "signedContext": {
          "type": "boolean",
          "title": "Expression Signed Context",
          "description": "Determines if this expression has signedContext."
        },
        "callerContext": {
          "type": "boolean",
          "title": "Expression Signed Context",
          "description": "Determines if this expression has callerContext."
        },
        "contextColumns": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ContextColumn"
          },
          "title": "Context Grid Columns",
          "description": "Specifies the reserved context grid columns of this expression, context is a 256x256 matrix of unit256.",
          "minItems": 1,
          "maxItems": 256
        }
      },
      "required": ["name", "abiName", "desc", "path"],
      "additionalProperties": false
    },
    "ContextColumn": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Context Column Name"
        },
        "desc": {
          "type": "string",
          "title": "Context Column Description"
        },
        "alias": {
          "type": "string",
          "title": "Context Column Alias",
          "description": "Alias for the context column used in RainLang, follows rainlang valid word pattern.",
          "pattern": "^[a-z][a-z0-9-]*$"
        },
        "columnIndex": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255,
          "title": "Context Column Index",
          "description": "Index of this context column grid, this value will be inside <> of associated interpreter's opcode, exxample: columnIndex: 0 -> context-column-opcode<0>."
        },
        "cells": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ContextCell"
          },
          "title": "Context Grid Cells",
          "description": "Specifies the reserved context grid cells of this expression, context is a 256x256 matrix of unit256.",
          "minItems": 1,
          "maxItems": 256
        }
      },
      "required": ["name", "alias", "columnIndex"],
      "additionalProperties": false
    },
    "ContextCell": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Context Cell Name"
        },
        "desc": {
          "type": "string",
          "title": "Context Cell Description"
        },
        "alias": {
          "type": "string",
          "title": "Context Cell Alias",
          "description": "Alias for the context cell used in RainLang, follows rainlang valid word pattern.",
          "pattern": "^[a-z][a-z0-9-]*$"
        },
        "cellIndex": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255,
          "title": "Context Cell Index",
          "description": "Index of this context cell grid, column index value and this value will be inside of <> of associated interpreter's opcode, example: columnIndex: 0, cellIndex: 1 -> context-cell-opcode<0 1>."
        }
      },
      "required": ["name", "alias", "cellIndex"],
      "additionalProperties": false
    }
  }
}

=== rainlanguage/orderbook-subgraph/contracts/sale/Sale.meta.json
{
  "name": "Sale",
  "abiName": "Sale",
  "desc": "Sale contract which throws a sale for reserve token against a redeemable erc20 token which can be later redeemed.",
  "alias": "sale",
  "source": "https://github.com/rainprotocol/rain-protocol",
  "methods": [
    {
      "name": "initialize",
      "abiName": "initialize",
      "desc": "Initialize a new Sale contract.",
      "inputs": [
        {
          "name": "Recepient Address",
          "abiName": "recipient",
          "desc": "The recipient of the proceeds of a Sale, if/when the Sale is successful.",
          "path": "[14].inputs[1].components[0]"
        },
        {
          "name": "Reserve Token Address",
          "abiName": "reserve",
          "desc": "The reserve token address that the Sale is deonominated in.",
          "path": "[14].inputs[1].components[1]"
        },
        {
          "name": "Sale Timeout",
          "abiName": "saleTimeout",
          "desc": "The number of seconds before this sale can timeout. SHOULD be well after the expected end time as a timeout will fail an active or pending sale regardless of any funds raised.",
          "path": "[14].inputs[1].components[2]"
        },
        {
          "name": "Cooldown Duration",
          "abiName": "cooldownDuration",
          "desc": "Forwarded to `Cooldown` contract initialization.",
          "path": "[14].inputs[1].components[3]"
        },
        {
          "name": "Minimum Raise Threshold",
          "abiName": "minimumRaise",
          "desc": "Defines the amount of reserve required to raise that defines success/fail of the sale. Reaching the minimum raise DOES NOT cause the raise to end early (unless the 'can live' expression allows it of course).",
          "path": "[14].inputs[1].components[4]"
        },
        {
          "name": "Dust Size",
          "abiName": "dustSize",
          "desc": "The minimum amount of rTKN that must remain in the Sale contract unless it is all purchased, clearing the raise to 0 stock and thus ending the raise.",
          "path": "[14].inputs[1].components[5]"
        },
        {
          "name": "Reddemable ERC20 Name",
          "abiName": "name",
          "desc": "Name of the Redeemable ERC20 token as defined by Open Zeppelin ERC20.",
          "path": "[14].inputs[2].components[0].components[0]"
        },
        {
          "name": "Reddemable ERC20 Symbol",
          "abiName": "symbol",
          "desc": "Symbol of the Redeemable ERC20 token as defined by Open Zeppelin ERC20.",
          "path": "[14].inputs[2].components[0].components[1]"
        },
        {
          "name": "Reddemable ERC20 Distributor",
          "abiName": "distributor",
          "desc": "Reddemable ERC20 distributor address of the initial supply, MAY be zero.",
          "path": "[14].inputs[2].components[0].components[2]"
        },
        {
          "name": "Reddemable ERC20 Initial Supply",
          "abiName": "initialSupply",
          "desc": "Redeemable ERC20 Initial supply to mint, MAY be zero.",
          "path": "[14].inputs[2].components[0].components[3]"
        },
        {
          "name": "Tier Address",
          "abiName": "tier",
          "desc": "Tier contract address to gate the sale",
          "path": "[14].inputs[2].components[1]"
        },
        {
          "name": "Minimum Tier",
          "abiName": "minimumTier",
          "desc": "Minimum tier level of the Tier contract that is gating the sale required in order to be able to participate in the sale",
          "path": "[14].inputs[2].components[2]"
        },
        {
          "name": "Distribution End Forwarding Address",
          "abiName": "distributionEndForwardingAddress",
          "desc": "Determines if the remaining Redeemable ERC20 tokens after the sale has ended in success should be burned or transfered to the Recepient address, 0x00 address would burn the remaining rTKNs.",
          "path": "[14].inputs[2].components[3]"
        }
      ],
      "expressions": [
        {
          "name": "Sale Expression",
          "abiName": "evaluableConfig",
          "desc": "An expression to calculate the rTKN price and sale's can live state.",
          "path": "[14].inputs[1].components[6]",
          "contextColumns": [
            {
              "name": "Base",
              "desc": "Base context column",
              "alias": "base",
              "columnIndex": 0,
              "cells": [
                {
                  "name": "Caller",
                  "desc": "The contract or EOA that called transfer",
                  "alias": "caller",
                  "cellIndex": 0
                },
                {
                  "name": "This Contract",
                  "desc": "The address of the Sale contract this expression is for",
                  "alias": "this-contract",
                  "cellIndex": 1
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

=== rainlanguage/orderbook-subgraph/contracts/stake/Stake.meta.json
{
  "name": "Stake",
  "abiName": "Stake",
  "desc": "Stake contract which allows for staking a ERC20 token as an asset.",
  "alias": "stake",
  "source": "https://github.com/rainprotocol/rain-protocol",
  "methods": [
    {
      "name": "initialize",
      "abiName": "initialize",
      "desc": "Initialize a new Stake contract.",
      "inputs": [
        {
          "name": "Asset",
          "abiName": "asset",
          "desc": "The underlying ERC20 asset for the 4626 vault.",
          "path": "[15].inputs[1].components[0]"
        },
        {
          "name": "Name",
          "abiName": "name",
          "desc": "ERC20 name of the 4626 share token to be minted.",
          "path": "[15].inputs[1].components[1]"
        },
        {
          "name": "Symbol",
          "abiName": "symbol",
          "desc": "ERC20 symbol of the 4626 share token to be minted.",
          "path": "[15].inputs[1].components[2]"
        }
      ],
      "expressions": [
        {
          "name": "Stake Desposits and Withdrawal Range",
          "abiName": "evaluableConfig",
          "desc": "An expression to calculate max deposits and withdrawals.",
          "path": "[15].inputs[1].components[3]",
          "signedContext": true,
          "callerContext": true,
          "contextColumns": [
            {
              "name": "Base",
              "desc": "Base context column",
              "alias": "base",
              "columnIndex": 0,
              "cells": [
                {
                  "name": "Caller",
                  "desc": "The contract or EOA that called transfer",
                  "alias": "caller",
                  "cellIndex": 0
                },
                {
                  "name": "This Contract",
                  "desc": "The address of the Stake contract this expression is for",
                  "alias": "this-contract",
                  "cellIndex": 1
                }
              ]
            },
            {
              "name": "Vault action",
              "desc": "Information about the vault action.",
              "alias": "vault-action",
              "columnIndex": 1,
              "cells": [
                {
                  "name": "Account",
                  "desc": "The account that the vault action is for.",
                  "alias": "account",
                  "cellIndex": 0
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

=== rainlanguage/orderbook-subgraph/contracts/lobby/Lobby.meta.json
{
  "name": "Lobby",
  "abiName": "Lobby",
  "desc": "",
  "source": "https://github.com/rainprotocol/rain-protocol",
  "alias": "lobby",
  "methods": [
    {
      "name": "initialize",
      "abiName": "initialize",
      "desc": "Initialize a Lobby Contract",
      "inputs": [
        {
          "name": "Ref must agree",
          "abiName": "refMustAgree",
          "desc": "If `true` the ref must agree to be the ref before ANY players can join. This guards against the ref being entirely unaware of the lobby and therefore unlikely to sign any data beyond generic results. This MAY be `false` if the outcome of the `Lobby` can be inferred by entirely generic data that the ref is likely to publish regardless of the `Lobby`, such as a winner list that can be produced upon demand from some API.",
          "path": "[11].inputs[1].components[0]"
        },
        {
          "name": "Referee",
          "abiName": "ref",
          "desc": "The ref is some address that is expected to provide signatures of the results that allow the `Lobby` to complete or move to invalid.",
          "path": "[11].inputs[1].components[1]"
        },
        {
          "name": "Token",
          "abiName": "token",
          "desc": "The token that fees and rewards will be denominated in.",
          "path": "[11].inputs[1].components[2]"
        },
        {
          "name": "Description",
          "abiName": "description",
          "desc": "IPFS hash or similar of description and rules etc. that can be in JSON for a GUI.",
          "path": "[11].inputs[1].components[4]"
        },
        {
          "name": "Timeout duration",
          "abiName": "timeoutDuration",
          "desc": "Timeout the whole lobby after this many seconds.",
          "path": "[11].inputs[1].components[5]"
        }
      ],
      "expressions": [
        {
          "name": "Lobby expression",
          "abiName": "evaluableConfig",
          "desc": "The expression that defines the rules for this Lobby.",
          "path": "[11].inputs[1].components[3]",
          "signedContext": true,
          "callerContext": true
        }
      ]
    }
  ]
}

=== rainlanguage/orderbook-subgraph/contracts/tier/CombineTier.meta.json
{
  "name": "CombineTier",
  "abiName": "CombineTier",
  "desc": "CombineTier which is a tier contract to combine reports of some other tier contracts based on an expression.",
  "alias": "combine-tier",
  "source": "https://github.com/rainprotocol/rain-protocol",
  "methods": [
    {
      "name": "initialize",
      "abiName": "initialize",
      "desc": "Initialize a new CombineTier contract.",
      "inputs": [
        {
          "name": "combinedTiersLength",
          "abiName": "combinedTiersLength",
          "desc": "The first N values in the constants array of the expressionConfig MUST be all the combined tiers that are known statically. Of course some tier addresses MAY only be known at runtime and so these cannotbe included.",
          "path": "[4].inputs[1].components[0]"
        }
      ],
      "expressions": [
        {
          "name": "CombineTier Expression",
          "abiName": "evaluableConfig",
          "desc": "An expression that determines the report of a CombineTier contract.",
          "path": "[4].inputs[1].components[1]",
          "signedContext": true,
          "callerContext": true
        }
      ]
    }
  ]
}
