=== rainlanguage/orderbook-subgraph/schema/meta/v0/op.meta.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/OpMeta",
  "$comment": "v0.0.1",
  "definitions": {
    "OpMeta": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Opcode Name",
          "description": "The primary word used to identify the opcode.",
          "pattern": "^[a-z][0-9a-z-]*$"
        },
        "desc": {
          "type": "string",
          "title": "Opcode Description",
          "description": "Describes what the opcode does briefly."
        },
        "operand": {
          "$ref": "#/definitions/OperandMeta",
          "title": "Opcode Operand",
          "description": "Data required in order to calculate and format the operand."
        },
        "inputs": {
          "$ref": "#/definitions/InputMeta",
          "title": "Opcode Inputs",
          "description": "Data required to specify the inputs of the opcode. 0 for opcodes with no input, for opcodes with constant number of inputs, the length of \"parameters\" array defines the number of inputs and for opcodes with dynamic number of inputs, \"bits\" field must be specified which determines this opcode has dynamic inputs and number of inputs will be derived from the operand bits with \"computation\" field applied if specified."
        },
        "outputs": {
          "$ref": "#/definitions/OutputMeta",
          "title": "Opcode Outputs",
          "description": "Data required to specify the outputs of the opcode. An integer specifies the number of outputs for opcodes with constants number of outputs and for opcodes with dynamic outputs the \"bits\" field will determine the number of outputs with \"computation\" field applied if specified."
        },
        "aliases": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[a-z][0-9a-z-]*$"
          },
          "title": "Opcode Aliases",
          "description": "Extra word used to identify the opcode."
        }
      },
      "required": ["name", "desc", "operand", "inputs", "outputs"],
      "additionalProperties": false,
      "title": "Opcode Metadata",
      "description": "Schema for opcodes metadata used by RainLang."
    },
    "OperandMeta": {
      "anyOf": [
        {
          "type": "integer",
          "const": 0
        },
        {
          "$ref": "#/definitions/OperandArgs"
        }
      ]
    },
    "OperandArgs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "bits": {
            "type": "array",
            "items": {
              "type": "integer",
              "minimum": 0,
              "maximum": 15
            },
            "minItems": 2,
            "maxItems": 2,
            "title": "Allocated Operand Bits",
            "description": "Specifies the bits to allocate to this operand argument."
          },
          "name": {
            "type": "string",
            "title": "Operand Argument Name",
            "description": "Name of the operand argument. Argument with the name of \"inputs\" is reserved so that it wont be be typed inside <> and its value needed to construct the operand will be the number of items inside the opcode's parens (computation will apply to this value if provided).",
            "pattern": "^[a-z][0-9a-z-]*$"
          },
          "desc": {
            "type": "string",
            "title": "Operand Argument Description",
            "description": "Description of the operand argument."
          },
          "computation": {
            "type": "string",
            "title": "Allocated Operand Bits Computation",
            "description": "Specifies any arithmetical operation that needs to be applied to the value of this operand argument. It will apply to the value before it be validated by the provided range. The \"arg\" keyword is reserved for accessing the value of this operand argument, example: \"(arg + 1) * 2\"."
          },
          "validRange": {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "array",
                  "items": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 65535
                  },
                  "minItems": 1,
                  "maxItems": 1
                },
                {
                  "type": "array",
                  "items": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 65535
                  },
                  "minItems": 2,
                  "maxItems": 2
                }
              ]
            },
            "title": "Operand Argument Range",
            "description": "Determines the valid range of the operand argument after computation applied. For example an operand argument can be any value between range of 1 - 10: [[1, 10]] or an operand argument can only be certain exact values: [[2], [3], [9]], meaning it can only be 2 or 3 or 9."
          }
        },
        "required": ["bits", "name"],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "InputMeta": {
      "anyOf": [
        {
          "type": "integer",
          "const": 0
        },
        {
          "$ref": "#/definitions/InputArgs"
        }
      ]
    },
    "InputArgs": {
      "type": "object",
      "properties": {
        "parameters": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "title": "Input Parameter Name",
                "description": "Name of the input parameter.",
                "pattern": "^[a-z][0-9a-z-]*$"
              },
              "desc": {
                "type": "string",
                "title": "Input Parameter Description",
                "description": "Description of the input parameter."
              },
              "spread": {
                "type": "boolean",
                "title": "Parameter Spread",
                "description": "Specifies if an argument is dynamic in length, default is false, so only needs to be defined if an argument is spread."
              }
            },
            "required": ["name"],
            "additionalProperties": false
          },
          "title": "Parameters",
          "description": "Data type for opcode's inputs parameters, the length determines the number of inputs for constant (non-computed) inputs."
        },
        "bits": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 0,
            "maximum": 15
          },
          "minItems": 2,
          "maxItems": 2,
          "title": "Inputs-Allocated Operand Bits",
          "description": "Specifies bits of the operand allocated for number of inputs. Determines the number of inputs for a computed opcode inputs. Required only for computed (non-constant) inputs."
        },
        "computation": {
          "type": "string",
          "title": "Inputs-Allocated Operand Bits Computation",
          "description": "Specifies any arithmetical operation that will be applied to the value of the extracted operand bits. The \"bits\" keyword is reserved for accessing the exctraced value, example: \"(bits + 1) * 2\". Required only for computed (non-constant) inputs."
        }
      },
      "required": ["parameters"],
      "additionalProperties": false
    },
    "OutputMeta": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0
        },
        {
          "$ref": "#/definitions/ComputedOutput"
        }
      ]
    },
    "ComputedOutput": {
      "type": "object",
      "properties": {
        "bits": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 0,
            "maximum": 15
          },
          "minItems": 2,
          "maxItems": 2,
          "title": "Outputs-Allocated Operand Bits",
          "description": "Specifies bits of the operand allocated for number of outputs. Determines the number of outputs for a computed opcode outputs. Required only for computed (non-constant) outputs."
        },
        "computation": {
          "type": "string",
          "title": "Outputs-Allocated Operand Bits Computation",
          "description": "Specifies any arithmetical operation that will be applied to the value of the extracted operand bits. The \"bits\" keyword is reserved for accessing the exctraced value, example: \"(bits + 1) * 2\". Required only for computed (non-constant) outputs."
        }
      },
      "required": ["bits"],
      "additionalProperties": false
    }
  }
}

=== rainlanguage/orderbook-subgraph/contracts/interpreter/ops/math/prb/OpPRBAvg.opmeta.json
{
  "name": "prb-avg",
  "desc": "Calculates the arithmetic average of x and y, as 18 decimal fixed point, rounding down.",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "x"
      },
      {
        "name": "y"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["decimal18-avg"]
}

=== rainlanguage/orderbook-subgraph/contracts/interpreter/ops/math/OpExp.opmeta.json
{
  "name": "exp",
  "desc": "Raises multiple integer values as powers of each other, e.g. x ^ y ^ z.",
  "operand": [
    {
      "name": "inputs",
      "bits": [0, 7],
      "validRange": [[2, 255]]
    }
  ],
  "inputs": {
    "bits": [0, 7],
    "parameters": [
      {
        "name": "input",
        "spread": true
      }
    ]
  },
  "outputs": 1,
  "aliases": ["int-pow"]
}

=== rainlanguage/orderbook-subgraph/contracts/interpreter/ops/math/saturating/OpSaturatingAdd.opmeta.json
{
  "name": "saturating-add",
  "desc": "Inserts sum of the specified items from the stack and if prevernts reverts if the result goes above max 256 bit size",
  "operand": [
    {
      "name": "inputs",
      "bits": [0, 7],
      "validRange": [[2, 255]]
    }
  ],
  "inputs": {
    "bits": [0, 7],
    "parameters": [
      {
        "name": "input",
        "spread": true
      }
    ]
  },
  "outputs": 1,
  "aliases": ["sat-add", "saturating-sum", "sat-sum"]
}

=== rainlanguage/orderbook-subgraph/contracts/interpreter/ops/math/logic/OpAny.opmeta.json
{
  "name": "any",
  "desc": "Inserts the first non-zero value of all the values it checks if there exists one, else inserts zero into the stack.",
  "operand": [
    {
      "name": "inputs",
      "bits": [0, 7],
      "validRange": [[2, 255]]
    }
  ],
  "inputs": {
    "bits": [0, 7],
    "parameters": [
      {
        "name": "input",
        "spread": true
      }
    ]
  },
  "outputs": 1,
  "aliases": ["or"]
}

=== rainlanguage/orderbook-subgraph/contracts/interpreter/ops/tier/OpITierV2SelectLte.opmeta.json
{
  "name": "tier-v2-select-lte",
  "desc": "The result of selecting the less than equal to specified value taken from stack among number of reports by a logic and mode into the stack",
  "operand": [
    {
      "name": "logic",
      "desc": "select lte logic: every or any logic",
      "bits": [13, 13]
    },
    {
      "name": "mode",
      "desc": "select lte mode: min, max or first",
      "bits": [8, 9],
      "validRange": [[0, 2]]
    },
    {
      "name": "inputs",
      "bits": [0, 7],
      "validRange": [[1, 255]]
    }
  ],
  "inputs": {
    "bits": [0, 7],
    "parameters": [
      {
        "name": "reference-timestamp",
        "desc": "The timestamp to check the tier reports against"
      },
      {
        "name": "report",
        "desc": "The report to selectLte from",
        "spread": true
      }
    ]
  },
  "outputs": 1
}

=== rainlanguage/orderbook-subgraph/contracts/interpreter/ops/bytes32/OpDecode256.opmeta.json
{
  "name": "decode-256",
  "desc": "Decode a slice of bits out of a 256 bit value (anything on the stack).",
  "operand": [
    {
      "name": "start",
      "desc": "Bit index to start reading from.",
      "bits": [8, 15]
    },
    {
      "name": "length",
      "desc": "Number of bits to read from start.",
      "bits": [0, 7]
    }
  ],
  "inputs": {
    "parameters": [
      {
        "name": "source"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["slice-256"]
}

=== rainlanguage/orderbook-subgraph/contracts/interpreter/ops/rain/IOrderBookV2/OpIOrderBookV2VaultBalance.opmeta.json
{
  "name": "orderbook-v2-vault-balance",
  "desc": "The balance of an OrderBookV2 or OrderBookV1 vault.",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "orderbook-address",
        "desc": "The address of the IOrderBookV2"
      },
      {
        "name": "owner-address",
        "desc": "The address of the Owner of the vault"
      },
      {
        "name": "token-address",
        "desc": "The address of the Token"
      },
      {
        "name": "vault-id"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["orderbook-v1-vault-balance"]
}

=== rainlanguage/orderbook-subgraph/contracts/interpreter/ops/context/OpFoldContext.opmeta.json
{
  "name": "fold-context",
  "desc": "Performs a looped call over some inputs and some context rows specified by column start index and width.",
  "operand": [
    {
      "name": "inputs",
      "bits": [13, 15]
    },
    {
      "name": "row",
      "desc": "Starting row to loop from.",
      "bits": [10, 12]
    },
    {
      "name": "width",
      "desc": "Number of columns to loop over.",
      "bits": [7, 9]
    },
    {
      "name": "fold-column",
      "desc": "Starting column to loop over.",
      "bits": [4, 6]
    },
    {
      "name": "source-index",
      "desc": "Index of the source to run.",
      "bits": [0, 3]
    }
  ],
  "inputs": {
    "bits": [13, 15],
    "parameters": [
      {
        "name": "input",
        "spread": true
      }
    ]
  },
  "outputs": {
    "bits": [13, 15]
  }
}
